# Generated by Django 4.0.3 on 2022-04-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('production_year', models.SmallIntegerField(default=None)),
                ('description', models.TextField(max_length=200)),
                ('mode', models.CharField(choices=[(1, 'Singleplayer'), (2, 'Multiplayer')], max_length=15)),
                ('type', models.CharField(choices=[(1, 'First Person Shooter'), (2, 'Third Person Shooter'), (3, 'Strategy'), (4, 'MMORPG'), (5, 'RPG'), (6, 'Racing'), (7, 'Survival')], max_length=15)),
            ],
        ),
    ]
