# Generated by Django 4.0.3 on 2022-04-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Modes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField(choices=[(1, 'Singleplayer'), (2, 'Multiplayer')], default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'First Person Shooter'), (2, 'Third Person Shooter'), (3, 'Strategy'), (4, 'MMORPG'), (5, 'RPG'), (6, 'Racing'), (7, 'Survival')], default=None)),
            ],
            options={
                'verbose_name': 'Game Type',
            },
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Title'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='game',
            name='type',
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
