# Generated by Django 4.0.3 on 2022-04-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_modes_game_type_alter_game_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game_modes',
            options={'verbose_name': 'Game Mode'},
        ),
    ]
