# Generated by Django 4.0.3 on 2022-04-03 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_modes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game_modes'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game_type'),
        ),
    ]
