# Generated by Django 4.0.3 on 2022-04-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_game_mode_alter_game_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_modes',
            name='mode',
            field=models.CharField(choices=[(' MP', 'Multiplayer'), ('SP', 'Singleplayer')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='game_type',
            name='type',
            field=models.CharField(choices=[('First Person Shooter', 'First Person Shooter'), ('Third Person Shooter', 'Third Person Shooter'), ('Strategy', 'Strategy'), ('MMORPG', 'MMORPG'), ('Racing', 'Racing'), ('Survival', 'Survival')], default=None, max_length=30),
        ),
    ]
