# Generated by Django 4.0.3 on 2022-04-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_remove_game_game_mode_game_game_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_mode',
        ),
        migrations.AddField(
            model_name='game',
            name='game_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game_modes'),
        ),
    ]
