# Generated by Django 4.0.3 on 2022-04-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_remove_game_game_mode_game_game_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_modes',
            name='games',
            field=models.ManyToManyField(to='games.game_type'),
        ),
        migrations.AlterField(
            model_name='game_modes',
            name='mode',
            field=models.CharField(choices=[(' Multiplayer', 'Multiplayer'), ('Singleplayer', 'Singleplayer')], default=None, max_length=30),
        ),
    ]
