# Generated by Django 4.0.3 on 2022-04-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_game_modes_games_alter_game_modes_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_modes',
            name='games',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_type',
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.ManyToManyField(to='games.game_type'),
        ),
    ]
