# Generated by Django 4.0.3 on 2022-04-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_remove_game_game_mode_game_game_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='shortcut',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
